/* =========================================================
   PLSQL Homework
   Part 1: Debugging framework
   Part 2: Salary adjustment procedure using the framework
   ========================================================= */


/* =========================================================
   STEP 0. Cleanup section
   Drop objects if they already exist.
   This allows the worksheet to be rerun multiple times.
   ========================================================= */

BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE adjust_salaries_by_commission';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE debug_utils';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE debug_log';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE employees';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

/* =========================================================
   STEP 1. Create the logging table
   This table stores:
   - when the log was created
   - from which module/procedure
   - the logical line/step number
   - the message itself
   - the Oracle session id

   This directly covers the assignment requirement for a
   logging table named DEBUG_LOG.
   ========================================================= */

CREATE TABLE debug_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_time TIMESTAMP DEFAULT SYSTIMESTAMP,
    module_name VARCHAR2(100),
    line_no NUMBER,
    log_message VARCHAR2(4000),
    session_id VARCHAR2(50) DEFAULT SYS_CONTEXT('USERENV', 'SESSIONID')
);

/* =========================================================
   STEP 2. Create a local EMPLOYEES table for testing
   This is not part of the framework itself, but it makes
   the homework runnable even if the HR sample schema is
   not available.
   ========================================================= */

CREATE TABLE employees (
    employee_id NUMBER PRIMARY KEY,
    first_name VARCHAR2(50),
    salary NUMBER(10,2),
    commission_pct NUMBER(5,2)
);

/* =========================================================
   STEP 3. Insert test data
   Two employees have commission_pct values.
   Two employees have NULL commission_pct values.
   This helps test both branches of the procedure logic.
   ========================================================= */

INSERT INTO employees VALUES (1, 'Alice', 3000, 0.10);
INSERT INTO employees VALUES (2, 'Bob',   4000, NULL);
INSERT INTO employees VALUES (3, 'Carol', 5000, 0.20);
INSERT INTO employees VALUES (4, 'David', 3500, NULL);

COMMIT;

/* =========================================================
   STEP 4. Create package specification
   This package centralizes all debugging operations.

   g_debug_mode:
   - TRUE  = logging enabled
   - FALSE = logging disabled

   The package exposes reusable procedures for:
   - enabling debug mode
   - disabling debug mode
   - logging messages
   - logging variable values
   - logging errors
   ========================================================= */

CREATE OR REPLACE PACKAGE debug_utils AS

    /* Global flag controlling whether normal logs are written */
    g_debug_mode BOOLEAN := FALSE;

    /* Turn debug logging on */
    PROCEDURE enable_debug;

    /* Turn debug logging off */
    PROCEDURE disable_debug;

    /* Log a generic execution message */
    PROCEDURE log_msg(
        p_module_name VARCHAR2,
        p_line_no     NUMBER,
        p_message     VARCHAR2
    );

    /* Log a variable name/value pair */
    PROCEDURE log_variable(
        p_module_name VARCHAR2,
        p_line_no     NUMBER,
        p_name        VARCHAR2,
        p_value       VARCHAR2
    );

    /* Log an error message */
    PROCEDURE log_error(
        p_proc VARCHAR2,
        p_err  VARCHAR2
    );

END debug_utils;
/

/* =========================================================
   STEP 5. Create package body
   This contains the actual implementation.

   Important adaptation:
   - log_error uses PRAGMA AUTONOMOUS_TRANSACTION
   so that error logs are preserved even if the main
   transaction is rolled back.

   This is a useful improvement for real debugging.
   ========================================================= */

CREATE OR REPLACE PACKAGE BODY debug_utils AS

    PROCEDURE enable_debug IS
    BEGIN
        g_debug_mode := TRUE;
    END enable_debug;

    PROCEDURE disable_debug IS
    BEGIN
        g_debug_mode := FALSE;
    END disable_debug;

    PROCEDURE log_msg(
        p_module_name VARCHAR2,
        p_line_no     NUMBER,
        p_message     VARCHAR2
    ) IS
    BEGIN
        IF g_debug_mode THEN
            INSERT INTO debug_log (module_name, line_no, log_message)
            VALUES (p_module_name, p_line_no, p_message);
        END IF;
    END log_msg;

    PROCEDURE log_variable(
        p_module_name VARCHAR2,
        p_line_no     NUMBER,
        p_name        VARCHAR2,
        p_value       VARCHAR2
    ) IS
    BEGIN
        IF g_debug_mode THEN
            INSERT INTO debug_log (module_name, line_no, log_message)
            VALUES (p_module_name, p_line_no, p_name || ' = ' || p_value);
        END IF;
    END log_variable;

    PROCEDURE log_error(
        p_proc VARCHAR2,
        p_err  VARCHAR2
    ) IS
        PRAGMA AUTONOMOUS_TRANSACTION;
    BEGIN
        /* Error logs are always stored, even if debug mode is off */
        INSERT INTO debug_log (module_name, line_no, log_message)
        VALUES (
            p_proc,
            NULL,
            'ERROR: ' || p_err || ' | BACKTRACE: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE
        );

        COMMIT;
    END log_error;

END debug_utils;
/

/* =========================================================
   STEP 6. Unit test the framework itself
   Before using the package in the main procedure, test that
   normal logging works correctly.
   ========================================================= */

BEGIN
    debug_utils.enable_debug;

    debug_utils.log_msg('TEST_DEBUG_FRAMEWORK', 1, 'Debug mode enabled successfully');
    debug_utils.log_variable('TEST_DEBUG_FRAMEWORK', 2, 'sample_variable', '123');

    debug_utils.disable_debug;
END;
/

/* =========================================================
   STEP 7. Check framework test output
   At this point, the DEBUG_LOG table should contain test rows.
   ========================================================= */

SELECT *
FROM debug_log
ORDER BY log_id;

/* =========================================================
   STEP 8. Create the main procedure
   Business rule from assignment:
   - if commission_pct is NOT NULL:
       increase salary proportionally by that percentage
   - if commission_pct IS NULL:
       increase salary by 2%

   The procedure also logs important steps:
   - start
   - employee read
   - salary/commission values
   - chosen calculation branch
   - new salary
   - update completed
   - procedure end
   ========================================================= */

CREATE OR REPLACE PROCEDURE adjust_salaries_by_commission IS

    /* Explicit cursor requested/allowed by the assignment */
    CURSOR emp_cursor IS
        SELECT employee_id, salary, commission_pct
        FROM employees;

    /* Anchored type: follows the data type of employees.salary */
    v_new_salary employees.salary%TYPE;

BEGIN
    /* Enable debug logging for this run */
    debug_utils.enable_debug;

    debug_utils.log_msg(
        'adjust_salaries_by_commission',
        1,
        'Procedure started'
    );

    FOR rec IN emp_cursor LOOP

        /* Log which employee is being processed */
        debug_utils.log_msg(
            'adjust_salaries_by_commission',
            2,
            'Processing employee_id = ' || rec.employee_id
        );

        /* Log current input values */
        debug_utils.log_variable(
            'adjust_salaries_by_commission',
            3,
            'Current salary',
            TO_CHAR(rec.salary)
        );

        debug_utils.log_variable(
            'adjust_salaries_by_commission',
            4,
            'Commission pct',
            NVL(TO_CHAR(rec.commission_pct), 'NULL')
        );

        /* Apply assignment rule */
        IF rec.commission_pct IS NOT NULL THEN
            v_new_salary := rec.salary + (rec.salary * rec.commission_pct);

            debug_utils.log_msg(
                'adjust_salaries_by_commission',
                5,
                'Commission-based increase applied'
            );
        ELSE
            v_new_salary := rec.salary * 1.02;

            debug_utils.log_msg(
                'adjust_salaries_by_commission',
                6,
                'Default 2% increase applied'
            );
        END IF;

        /* Log the computed result */
        debug_utils.log_variable(
            'adjust_salaries_by_commission',
            7,
            'New salary',
            TO_CHAR(v_new_salary)
        );

        /* Update the employee record */
        UPDATE employees
        SET salary = v_new_salary
        WHERE employee_id = rec.employee_id;

        debug_utils.log_msg(
            'adjust_salaries_by_commission',
            8,
            'Salary updated for employee_id = ' || rec.employee_id
        );

    END LOOP;

    COMMIT;

    debug_utils.log_msg(
        'adjust_salaries_by_commission',
        9,
        'Procedure completed successfully'
    );

    debug_utils.disable_debug;

EXCEPTION
    WHEN OTHERS THEN
        /* Log the exception in a reusable, uniform way */
        debug_utils.log_error('adjust_salaries_by_commission', SQLERRM);
        ROLLBACK;
        RAISE;
END adjust_salaries_by_commission;
/

/* =========================================================
   STEP 9. Execute the procedure
   ========================================================= */

BEGIN
    adjust_salaries_by_commission;
END;
/

/* =========================================================
   STEP 10. Verify business results
   Expected:
   - Alice: 3000 -> 3300   (10%)
   - Bob:   4000 -> 4080   (2%)
   - Carol: 5000 -> 6000   (20%)
   - David: 3500 -> 3570   (2%)
   ========================================================= */

SELECT *
FROM employees
ORDER BY employee_id;

/* =========================================================
   STEP 11. Verify log output
   The table should now contain:
   - framework test logs
   - detailed procedure execution logs
   ========================================================= */

SELECT log_id,
       log_time,
       module_name,
       line_no,
       log_message,
       session_id
FROM debug_log
ORDER BY log_id;