-- Drop objects if they already exist (ignore errors if they don’t)

BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE adjust_salaries_by_commission';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE debug_utils';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE debug_log';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE employees';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
----------------
CREATE TABLE debug_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_time TIMESTAMP DEFAULT SYSTIMESTAMP,
    module_name VARCHAR2(100),
    line_no NUMBER,
    log_message VARCHAR2(4000),
    session_id VARCHAR2(50) DEFAULT SYS_CONTEXT('USERENV', 'SESSIONID')
);

-----------------
CREATE TABLE employees (
    employee_id NUMBER PRIMARY KEY,
    first_name VARCHAR2(50),
    salary NUMBER(10,2),
    commission_pct NUMBER(5,2)
);
------------
INSERT INTO employees VALUES (1, 'Alice', 3000, 0.10);
INSERT INTO employees VALUES (2, 'Bob', 4000, NULL);
INSERT INTO employees VALUES (3, 'Carol', 5000, 0.20);
INSERT INTO employees VALUES (4, 'David', 3500, NULL);

COMMIT;
-----------------
CREATE OR REPLACE PACKAGE debug_utils AS
    g_debug_mode BOOLEAN := FALSE;

    PROCEDURE enable_debug;
    PROCEDURE disable_debug;

    PROCEDURE log_msg(p_module_name VARCHAR2, p_line_no NUMBER, p_message VARCHAR2);
    PROCEDURE log_variable(p_module_name VARCHAR2, p_line_no NUMBER, p_name VARCHAR2, p_value VARCHAR2);
    PROCEDURE log_error(p_proc VARCHAR2, p_err VARCHAR2);
END debug_utils;

---------------
CREATE OR REPLACE PACKAGE BODY debug_utils AS

    PROCEDURE enable_debug IS
    BEGIN
        g_debug_mode := TRUE;
    END enable_debug;

    PROCEDURE disable_debug IS
    BEGIN
        g_debug_mode := FALSE;
    END disable_debug;

    PROCEDURE log_msg(p_module_name VARCHAR2, p_line_no NUMBER, p_message VARCHAR2) IS
    BEGIN
        IF g_debug_mode THEN
            INSERT INTO debug_log(module_name, line_no, log_message)
            VALUES (p_module_name, p_line_no, p_message);
        END IF;
    END log_msg;

    PROCEDURE log_variable(p_module_name VARCHAR2, p_line_no NUMBER, p_name VARCHAR2, p_value VARCHAR2) IS
    BEGIN
        IF g_debug_mode THEN
            INSERT INTO debug_log(module_name, line_no, log_message)
            VALUES (p_module_name, p_line_no, p_name || ' = ' || p_value);
        END IF;
    END log_variable;

    PROCEDURE log_error(p_proc VARCHAR2, p_err VARCHAR2) IS
    BEGIN
        INSERT INTO debug_log(module_name, line_no, log_message)
        VALUES (p_proc, NULL, 'ERROR: ' || p_err);
    END log_error;

END debug_utils;
//

----------------------
BEGIN
    debug_utils.enable_debug;

    debug_utils.log_msg('TEST', 1, 'Debug mode enabled');
    debug_utils.log_variable('TEST', 2, 'Sample variable', '123');

    debug_utils.disable_debug;
END;
/
---------------
SELECT * FROM debug_log ORDER BY log_id;
-----------------
CREATE OR REPLACE PROCEDURE adjust_salaries_by_commission IS

    CURSOR emp_cursor IS
        SELECT employee_id, salary, commission_pct
        FROM employees;

    v_new_salary employees.salary%TYPE;

BEGIN
    debug_utils.enable_debug;

    debug_utils.log_msg('adjust_salaries_by_commission', 1, 'Procedure started');

    FOR rec IN emp_cursor LOOP

        debug_utils.log_msg(
            'adjust_salaries_by_commission',
            2,
            'Processing employee_id = ' || rec.employee_id
        );

        debug_utils.log_variable(
            'adjust_salaries_by_commission',
            3,
            'Current salary',
            TO_CHAR(rec.salary)
        );

        debug_utils.log_variable(
            'adjust_salaries_by_commission',
            4,
            'Commission pct',
            NVL(TO_CHAR(rec.commission_pct), 'NULL')
        );

        IF rec.commission_pct IS NOT NULL THEN
            v_new_salary := rec.salary + (rec.salary * rec.commission_pct);

            debug_utils.log_msg(
                'adjust_salaries_by_commission',
                5,
                'Commission-based increase applied'
            );
        ELSE
            v_new_salary := rec.salary * 1.02;

            debug_utils.log_msg(
                'adjust_salaries_by_commission',
                6,
                'Default 2% increase applied'
            );
        END IF;

        debug_utils.log_variable(
            'adjust_salaries_by_commission',
            7,
            'New salary',
            TO_CHAR(v_new_salary)
        );

        UPDATE employees
        SET salary = v_new_salary
        WHERE employee_id = rec.employee_id;

        debug_utils.log_msg(
            'adjust_salaries_by_commission',
            8,
            'Salary updated for employee_id = ' || rec.employee_id
        );

    END LOOP;

    COMMIT;

    debug_utils.log_msg(
        'adjust_salaries_by_commission',
        9,
        'Procedure completed successfully'
    );

    debug_utils.disable_debug;

EXCEPTION
    WHEN OTHERS THEN
        debug_utils.log_error('adjust_salaries_by_commission', SQLERRM);
        ROLLBACK;
        RAISE;
END adjust_salaries_by_commission;
/
------------------
BEGIN
    adjust_salaries_by_commission;
END;
/
---------
SELECT * FROM employees ORDER BY employee_id;
--------------
SELECT log_id, log_time, module_name, line_no, log_message
FROM debug_log
ORDER BY log_id;